name: CI

on:
  push:
    branches:
      - main
      - project_files
      - files_git
      - azure-pipeline

env:
  EPIC_GAMES_USERNAME: ${{ secrets.EPIC_GAMES_USERNAME }}
  EPIC_GAMES_PASSWORD: ${{ secrets.EPIC_GAMES_PASSWORD }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Epic Games Launcher
        run: |
          Invoke-WebRequest -Uri "https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi?productName=unrealEngine" -OutFile "EpicGamesLauncherInstaller.msi"
          Start-Process -Wait -FilePath msiexec -ArgumentList '/i', 'EpicGamesLauncherInstaller.msi', '/quiet', '/qn', '/norestart'

      - name: Set Launcher Path
        id: set_launcher_path
        run: |
          $launcherPath = "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe"
          if (Test-Path "$launcherPath") {
            echo "::set-output name=launcherPath::$launcherPath"
          } else {
            Write-Error "Epic Games Launcher not found at the specified path."
          }

      - name: Sign In to Epic Games Account
        run: |
          $launcherPath = ${{ steps.set_launcher_path.outputs.launcherPath }}
          & "$launcherPath" login -username $env:EPIC_GAMES_USERNAME -password $env:EPIC_GAMES_PASSWORD

      - name: Install Unreal Engine
        run: |
          & "$launcherPath" '-run=UnrealEngine'

      - name: Build Unreal Engine Project
        run: |
          cd .\megascans_UE
          .\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=Project1.uproject -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive
