name: CI

on:
  push:
    branches:
      - main
      - project_files
      - files_git
      - azure-pipeline

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Unreal Engine
        run: |
          # Download Unreal Engine 5.11 installer
          Invoke-WebRequest -Uri "https://unrealengine.com/release/5.11.0/installer/UnrealEngineInstaller.exe" -OutFile "UnrealEngineInstaller.exe"

          # Install Unreal Engine silently
          Start-Process -Wait -FilePath .\UnrealEngineInstaller.exe -ArgumentList '-y'

          # Print version for verification
          .\Engine\Build\BatchFiles\RunUAT.bat version

      - name: Build Unreal Engine Project
        run: |
          # Navigate to the project directory
          cd .\megascans_UE

          # Run a basic build command (adjust as needed)
          .\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=Project1.uproject -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive
