name: CI

on:
  push:
    branches:
      - main
      - project_files
      - files_git
      - azure-pipeline

env:
  EPIC_GAMES_USERNAME: ${{ secrets.EPIC_GAMES_USERNAME }}
  EPIC_GAMES_PASSWORD: ${{ secrets.EPIC_GAMES_PASSWORD }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Epic Games Launcher
        run: |
          $launcherPath = "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe"
          Invoke-WebRequest -Uri "https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi?productName=unrealEngine" -OutFile "EpicGamesLauncherInstaller.msi"
          Start-Process -Wait -FilePath msiexec -ArgumentList '/i', 'EpicGamesLauncherInstaller.msi', '/quiet', '/qn', '/norestart'
          if (Test-Path $launcherPath) {
              Start-Process -Wait -FilePath $launcherPath -ArgumentList '-run=UnrealEngine', '-Login', '-username', $env:EPIC_GAMES_USERNAME, '-password', $env:EPIC_GAMES_PASSWORD -Verb RunAs
          } else {
              Write-Error "Epic Games Launcher not found at $launcherPath"
          }

      - name: Debug
        run: |
          Write-Output "Current directory: $PWD"
          Write-Output "List contents: $(Get-ChildItem)"

      - name: Build Unreal Engine Project
        run: |
          cd .\megascans_UE
          .\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=Project1.uproject -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive
