name: CI

on:
  push:
    branches:
      - main
      - project_files
      - files_git
      - azure-pipeline

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Unreal Engine
        uses: anuejn/action-setup-unreal@v1
        with:
          ueVersion: '4.27.0'

      - name: Build Game
        run: |
          .\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=C:\OneDrive\Documents\Portfolio_project1\Project1.uproject -noP4
        shell: cmd
